### PR TITLE
export qr_logo()

### PR DESCRIPTION
**Pull request by ThierryO**
@badgettrg, can you give feedback on this branch? Install it with `remotes::install_github("ThierryO/qrcode@hotfix")`

### CODE REVIEW

**Comment by badgettrg** [comment]
Image looks very good and retrieves the requested URL, and the svg opens in MS Edge on my Windows computer. However, I could not programmatically save it as a png with:
`png(file=paste(filename,'-logo.png',sep=''))`
`code <- qr_logo(x = url, logo = "logo.jpg", file=paste(filename,'..svg',sep=''))`
`plot (code)`
`dev.off()`

Error in plot.window(...) : need finite 'ylim' values
In addition: Warning messages:
1: In xy.coords(x, y, xlabel, ylabel, log) : NAs introduced by coercion
2: In min(x) : no non-missing arguments to min; returning Inf
3: In max(x) : no non-missing arguments to max; returning -Inf

**Comment by ThierryO** [comment]
Currently `qr_logo()` only writes the svg file and returns invisible `NULL`. Hence plotting it's output doesn't work. What is your use case for png that doesn't work with svg?

**Comment by badgettrg** [comment]
Good question.

The use case is to insert QR codes into PPTx files for interactive classrooms, or sometimes into Word files for posters. However, in response to your question, I just tested and found that I can drag and drop SVGs fine into these files. So no need for PNGs to avoid manual file conversions.

thanks much

bob
________________________________

**Comment by ThierryO** [comment]
@badgettrg can you try this version? `qr_logo()` now works like `qr_code()`. So you can `plot()` the output. Use `generate_svg()` in case you want an `svg` format.

**Comment by badgettrg** [comment]
When I try:
`remotes::install_github("ThierryO/qrcode", force = TRUE)` 
I get:
Skipping install of 'qrcode' from a github remote, the SHA1 (e610b2b9) has not changed since last install.

When I try
`remotes::install_github("ThierryO/qrcode@hotfix")`
I get version 0.2.0 and when I try
`code <- qr_logo(x = url, logo = "logo.jpg")`
I get:
Could not find function "qr_logo"

**Comment by ThierryO** [comment]
It looks like you reinstalled the hoxfix version (0.2.1) while the deploied version (0.2.0) was loaded. Can you try again in a clean session? It should load version 0.2.1. If not, close all R sessions, run `remotes::install_github("ThierryO/qrcode@hotfix", force = TRUE)` in a new R session before trying again.

**Comment by ThierryO** [comment]
That's deliberate in the current implementation. The logo is scale so the error correction level is preserved. A logo with an more extreme width to height ratio could overlap with the finder and timing patterns. The logo is scaled and center to the area to the right and below the finder and timing patterns. Centering to the entire code might result in a smaller logo (to avoid the overlap).
qr code pattern locations

Maybe I could add an `hjust` and `vjust` argument to indicate the relative position of the logo center. E.g. `hjust = 0.5` would place the center of the logo in the center of the qrcode. `hjust = 0.75` would place the center at a quarter to the right side. But what if the logo is wider than half the qr code in such case? Clip the logo? Move the logo to the left until it fits? Keep the location of the logo center and shrink the logo until it fits?

**Comment by badgettrg** [comment]
would it be easier to tell the user in the Help file the maximum or ideal logo size?
________________________________

**Comment by ThierryO** [comment]
@badgettrg and @markscherz, can you please test this version? I replaced `qr_logo()` with `add_logo()`. So you first generate a QR code and then add the logo. Hence it also works with `qr_event()` and `qr_wifi()`. The horizontal placement of the logo can be left, center or right. The vertical placement is either bottom, center or top.

Install it with `remotes::install_github("ThierryO/qrcode@hotfix")` in a clean R session.

**Comment by badgettrg** [comment]
The Rstudio help file displays "Internal Server Error" when I try to display help for add_logo so that I can see the parameters to pass.

But when I try
add_logo(code = code, logo = "logo.jpg")
I get:
Error: error level in `code` must be higher than `ecl` set in add_logo()
________________________________

**Comment by ThierryO** [comment]
`qr_code()` and `add_logo()` use by default the lowest error level (`"L"`). Adding a logo on top of a QR code decreases error level. Therefore you must provide a QR code with a higher error levels as input to `add_logo()`.

```
# largest difference in error level, hence largest logo
code <- qr_code("my text", ecl = "H")
add_logo(code, "logo.jpg")
# minimal difference, hence small logo
code <- qr_code("my text", ecl = "M")
add_logo(code, "logo.jpg")
code <- qr_code("my text", ecl = "H")
add_logo(code, "logo.jpg", ecl = "Q")
# error level in input too small
code <- qr_code("my text", ecl = "M")
add_logo(code, "logo.jpg", ecl = "H")
```

**Comment by badgettrg** [comment]
Great! The following works fine:
filename <- paste('qrcode-',domain,sep='')
if (logo == 1){filename <- paste(filename,'-logo',sep='')}
code <- qr_code(url, ecl = "H")
if (logo == 1){
  filename = paste('qrcode-',domain,'-logo',sep='')
  code <- add_logo(code = code, logo = "logo.jpg")
  }
# SVG
generate_svg(
  qrcode = code, filename = paste(filename,'.svg',sep=''), foreground = "#0022B4", show = FALSE
)
# PNG
png(file=paste(filename,'.png',sep=''))
plot(code)
dev.off()
Consider function qr_code accepting a foreground argument as generate_svg does.
________________________________

**Comment by badgettrg** [comment]
qr_code working very well.

Would like to handle a mailto link with subject line in order to solicit audience feedback at an oral presentation.

`mailto:rbadgett@kumc.edu?subject=test%20message`

...picks up the email address, but does not pick up the subject line

if you have time to add this enhancement, great. No worries if no time. thanks

**Comment by ThierryO** [comment]
The code below generates a qr code with the correct message. The problem is with the software scanning the code.

```
qrcode::qr_code("mailto:rbadgett@kumc.edu?subject=test%20message") |>
  plot()
```

**Pull request merged**
